import { PhotoPreset, Adjustments, CurvesData } from "@/types/editor";
import { DEFAULT_CURVES } from "@/components/CurvesTool";

export const DEFAULT_ADJUSTMENTS: Adjustments = {
  exposure: 0,
  brightness: 0,
  contrast: 0,
  highlights: 0,
  shadows: 0,
  whites: 0,
  blacks: 0,
  saturation: 0,
  vibrance: 0,
  temperature: 0,
  tint: 0,
  sharpness: 0,
  clarity: 0,
  blur: 0,
  grain: 0,
  vignette: 0,
};

export const PRESET_CATEGORIES = [
  "All",
  "Recommended",
  "Portrait",
  "Product",
  "Lifestyle",
  "Cinematic",
  "Black & White",
] as const;

export const PHOTO_PRESETS: PhotoPreset[] = [
  // --- 1. RECOMMENDED ---
  {
    id: "auto_enhance",
    name: "Auto Enhance",
    category: "Recommended",
    tag: "AUTO",
    description: "Balanced dynamic range recovery with natural color vibrance",
    previewBg: "from-[#0284c7] via-[#0369a1] to-[#0c4a6e]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 5,
      contrast: 8,
      highlights: -12,
      shadows: 14,
      saturation: 4,
      whites: 6,
      blacks: -4,
      vibrance: 8,
      clarity: 4,
    },
  },
  {
    id: "clean",
    name: "Clean",
    category: "Recommended",
    tag: "CLEAN",
    description: "Neutral, true-to-life tones with gentle highlight control",
    previewBg: "from-[#3b82f6] via-[#1d4ed8] to-[#1e1b4b]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 3,
      contrast: 5,
      highlights: -8,
      shadows: 10,
      saturation: -2,
      whites: 4,
      blacks: -2,
      clarity: 4,
    },
  },
  {
    id: "vivid",
    name: "Vivid",
    category: "Recommended",
    tag: "VIVID",
    description: "Punchy color richness and boosted midtone contrast",
    previewBg: "from-[#f59e0b] via-[#ef4444] to-[#7c2d12]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 2,
      contrast: 14,
      highlights: -10,
      shadows: 8,
      saturation: 18,
      vibrance: 12,
      temperature: 2,
      clarity: 6,
      whites: 8,
    },
  },

  // --- 2. PORTRAIT ---
  {
    id: "portrait",
    name: "Portrait",
    category: "Portrait",
    tag: "SKIN",
    description: "Softened skin tones with gentle highlight preservation",
    previewBg: "from-[#fb923c] via-[#ea580c] to-[#7c2d12]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 4,
      contrast: -3,
      highlights: -12,
      shadows: 12,
      saturation: 3,
      vibrance: 8,
      temperature: 3,
      clarity: -4,
    },
  },
  {
    id: "warm_portrait",
    name: "Golden Hour Glow",
    category: "Portrait",
    tag: "GOLDEN",
    description: "Luminous amber warm tones and gentle edge vignette",
    previewBg: "from-[#d97706] via-[#b45309] to-[#451a03]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 6,
      contrast: 6,
      highlights: -10,
      shadows: 14,
      saturation: 8,
      vibrance: 14,
      temperature: 16,
      tint: 4,
      vignette: -12,
      clarity: -2,
    },
  },
  {
    id: "soft_editorial",
    name: "Soft Editorial",
    category: "Portrait",
    tag: "STUDIO",
    description: "High-end studio fashion look with lowered local contrast",
    previewBg: "from-[#f472b6] via-[#db2777] to-[#831843]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 5,
      contrast: -5,
      highlights: -15,
      shadows: 16,
      saturation: -4,
      vibrance: 6,
      temperature: 2,
      tint: 4,
      clarity: -8,
      grain: 8,
    },
  },

  // --- 3. PRODUCT ---
  {
    id: "product_clean",
    name: "Product Clean",
    category: "Product",
    tag: "COMMERCIAL",
    description: "Crisp product definition with bright specular highlights and deep blacks",
    previewBg: "from-[#10b981] via-[#047857] to-[#064e3b]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 5,
      contrast: 10,
      highlights: -15,
      shadows: 12,
      whites: 10,
      blacks: -5,
      saturation: 3,
      sharpness: 8,
      clarity: 5,
    },
  },
  {
    id: "food",
    name: "Food & Culinary",
    category: "Product",
    tag: "CULINARY",
    description: "Warm, appetizing colors with rich texture and enhanced vibrance",
    previewBg: "from-[#eab308] via-[#ca8a04] to-[#713f12]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 4,
      contrast: 12,
      highlights: -10,
      shadows: 10,
      saturation: 14,
      vibrance: 10,
      temperature: 6,
      clarity: 8,
      whites: 6,
    },
  },
  {
    id: "studio_white",
    name: "Packshot Studio",
    category: "Product",
    tag: "E-COMM",
    description: "Clean whites and sharp micro-texture for e-commerce catalog photos",
    previewBg: "from-[#94a3b8] via-[#64748b] to-[#1e293b]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 6,
      contrast: 14,
      highlights: -18,
      shadows: 10,
      whites: 14,
      blacks: -6,
      saturation: -2,
      sharpness: 12,
      clarity: 8,
    },
  },

  // --- 4. LIFESTYLE ---
  {
    id: "warm",
    name: "Warm Sunlight",
    category: "Lifestyle",
    tag: "WARM",
    description: "Comfortable amber warmth with lifted shadows",
    previewBg: "from-[#f97316] via-[#c2410c] to-[#7c2d12]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 2,
      contrast: 5,
      highlights: -8,
      shadows: 8,
      saturation: 5,
      temperature: 10,
      vibrance: 6,
    },
  },
  {
    id: "cool",
    name: "Nordic Cool",
    category: "Lifestyle",
    tag: "COOL",
    description: "Crisp atmospheric blues and modern urban tones",
    previewBg: "from-[#06b6d4] via-[#0891b2] to-[#164e63]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 1,
      contrast: 7,
      highlights: -6,
      shadows: 6,
      saturation: 2,
      temperature: -10,
    },
  },
  {
    id: "matte",
    name: "Matte Film",
    category: "Lifestyle",
    tag: "MATTE",
    description: "Raised blacks with analog film aesthetic and subtle grain",
    previewBg: "from-[#854d0e] via-[#713f12] to-[#1c1917]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 3,
      contrast: -8,
      highlights: -5,
      shadows: 12,
      whites: -6,
      blacks: 18,
      saturation: -5,
      clarity: -4,
      grain: 16,
    },
  },

  // --- 5. CINEMATIC ---
  {
    id: "cinematic",
    name: "Cinematic Teal",
    category: "Cinematic",
    tag: "CINEMA",
    description: "Dramatic high contrast movie grade with edge vignette",
    previewBg: "from-[#0d9488] via-[#115e59] to-[#042f2e]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: -2,
      contrast: 18,
      highlights: -18,
      shadows: 5,
      whites: 4,
      blacks: -4,
      saturation: -4,
      temperature: -3,
      tint: 2,
      vignette: 12,
      grain: 8,
    },
  },
  {
    id: "night",
    name: "Night Vision",
    category: "Cinematic",
    tag: "NIGHT",
    description: "Optimized for low-light cityscapes and evening photography",
    previewBg: "from-[#4338ca] via-[#312e81] to-[#0f172a]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: -3,
      contrast: 12,
      highlights: -20,
      shadows: 15,
      saturation: 5,
      temperature: -4,
      tint: -2,
      vignette: 8,
      clarity: 10,
    },
  },
  {
    id: "cyberpunk",
    name: "Cyber Neon",
    category: "Cinematic",
    tag: "NEON",
    description: "Vibrant neon magenta and cyan grade with stylized contrast",
    previewBg: "from-[#ec4899] via-[#8b5cf6] to-[#1e1b4b]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 2,
      contrast: 22,
      highlights: -14,
      shadows: 8,
      saturation: 25,
      vibrance: 18,
      temperature: -8,
      tint: 20,
      vignette: 18,
      clarity: 12,
    },
  },

  // --- 6. BLACK & WHITE ---
  {
    id: "bw_classic",
    name: "Black & White",
    category: "Black & White",
    tag: "B&W",
    description: "Classic high dynamic range monochrome conversion",
    previewBg: "from-[#71717a] via-[#3f3f46] to-[#09090b]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      contrast: 15,
      highlights: -10,
      shadows: 10,
      whites: 8,
      blacks: -8,
      saturation: -100,
      clarity: 8,
    },
  },
  {
    id: "bw_high_contrast",
    name: "Silver Gelatin",
    category: "Black & White",
    tag: "SILVER",
    description: "Deep blacks, crisp specular whites, and analog film grain",
    previewBg: "from-[#52525b] via-[#27272a] to-[#000000]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: 2,
      contrast: 28,
      highlights: -14,
      shadows: 6,
      whites: 14,
      blacks: -14,
      saturation: -100,
      sharpness: 10,
      clarity: 14,
      grain: 22,
    },
  },
  {
    id: "bw_moody",
    name: "Moody Low-Key",
    category: "Black & White",
    tag: "LOW-KEY",
    description: "Dramatic shadows and rich tonal gradients",
    previewBg: "from-[#3f3f46] via-[#18181b] to-[#000000]",
    adjustments: {
      ...DEFAULT_ADJUSTMENTS,
      exposure: -4,
      contrast: 22,
      highlights: -24,
      shadows: -4,
      whites: 6,
      blacks: -12,
      saturation: -100,
      vignette: 24,
      grain: 14,
    },
  },
];
